import { Geist, Geist_Mono } from "next/font/google";
import { AuthProvider } from './context/AuthContext';
import "./globals.css";
import DevUnhandledLogger from './components/DevUnhandledLogger';
import SiteHeader from '../components/SiteHeader';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Joanna's Nook",
  description: "Generated by create next app",
  icons: {
    icon: "/Joannaslogo.png",
    shortcut: "/Joannaslogo.png",
    apple: "/apple-touch-icon.png",
  },
  viewport: "width=device-width, initial-scale=1",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          <DevUnhandledLogger />
          <SiteHeader />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
