import pool from "../../../lib/db";
import jwt from "jsonwebtoken";

export async function POST(req) {
  try {
    const payload = await req.json();
    let code = '';

    // Accept either { code: '...' } or a direct string-like body
    if (payload && typeof payload === 'object' && payload.code) {
      code = String(payload.code).trim();
    } else if (typeof payload === 'string') {
      code = payload.trim();
    }

    if (!code) {
      return Response.json({ message: "Missing or invalid QR code" }, { status: 400 });
    }

    // If the QR already contains a JWT, verify and return it
    if (code.includes('.') && process.env.JWT_SECRET) {
      try {
        const decoded = jwt.verify(code, process.env.JWT_SECRET);
        const userRes = await pool.query(
          "SELECT id, email, name, role FROM users WHERE id = $1",
          [decoded.id]
        );
        if (userRes.rows.length > 0) {
          return Response.json({ user: userRes.rows[0], token: code }, { status: 200 });
        }
      } catch (_) {
        // fall through to lookup by code
      }
    }

    // If the code looks like JSON (e.g., generated by staff QR), try parsing
    let parsed = null;
    try {
      if ((code.startsWith('{') && code.endsWith('}')) || code.includes('"userId"')) {
        parsed = JSON.parse(code);
      }
    } catch (_) {
      parsed = null;
    }

    let lookupKey = code;
    if (parsed && typeof parsed === 'object') {
      if (parsed.userId) lookupKey = String(parsed.userId);
      else if (parsed.email) lookupKey = String(parsed.email);
      else if (parsed.qr_code) lookupKey = String(parsed.qr_code);
    }

    // Lookup user by id or email text match
    // Note: some deployments may not have a qr_code column in the users table,
    // so we only match by id or email to avoid SQL errors.
    const query = `
      SELECT id, email, name, role
      FROM users
      WHERE (CAST(id AS TEXT) = $1)
         OR (LOWER(email) = LOWER($1))
      LIMIT 1
    `;
    const result = await pool.query(query, [lookupKey.trim()]);
    if (result.rows.length === 0) {
      return Response.json({ message: "QR not recognized" }, { status: 401 });
    }

    if (!process.env.JWT_SECRET) {
      throw new Error("Server configuration error");
    }
    const user = result.rows[0];
    const token = jwt.sign({ id: user.id, role: user.role }, process.env.JWT_SECRET, { expiresIn: "7d" });
    return Response.json({ user, token }, { status: 200 });
  } catch (error) {
    console.error("QR Login API Error:", error);
    return Response.json({ message: error.message || "Internal Server Error" }, { status: 500 });
  }
}


